# Generated by Django 4.2.7 on 2023-11-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testIdeNet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='internet',
            field=models.BooleanField(default=False, verbose_name='internet'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
    ]
